### ISSUE TITLE
Fetching error

### ISSUE THREAD

**Issue by stardock** [AoEiuV020/comic#1]
老大，这款神器突然出现了 fetching error 的报错
能抽空看看能搞好不？

**Comment by AoEiuV020** [comment]
捂脸，这个项目现在都没在维护了，打算以后重写的，我也不知道你是遇到什么问题了，

stardock <notifications@github.com> 于 2019年5月28日周二 12:23写道：

**Comment by stardock** [comment]
加载漫画列表失败
http error fetching URL
新项目是啥咩？去关注一下

**Comment by AoEiuV020** [comment]
另一个是爬小说的，打算直接往里面加入漫画支持，或者用爬小说的框架改成爬漫画，还没做，
https://github.com/AoEiuV020/PaNovel

stardock <notifications@github.com> 于2019年5月29日周三 下午12:19写道：

**Comment by stardock** [comment]
好的，等你的好消息
